### ISSUE TITLE
How to build your tool ?

### ISSUE THREAD

**Issue by PhamAn12** [dwat3r/slicer#4]
Hi guy, Can you give me some guidance for install and building your tool?

**Comment by dwat3r** [comment]
Hi, sorry for the very late reply.
It depends on which platform you would like to build it.
I've developed it in Visual Studio, on Windows, but with a generic cmake file which includes the source files, you can build it on linux or mac os too.
On windows, you need to have a downloaded clang source code,and set to link the necessary libraries to the executable.
If you're still interested, let me know
